[project]
name = "taxsim-py"
version = "0.1.0"
description = "A dataframe-oriented Python implementation of NBER TAXSIM"
requires-python = ">=3.10"
dependencies = [
    "polars>=1.44.2",
    "pyyaml>=6.0.3",
]

[dependency-groups]
test = [
    "policyengine-taxsim>=2.31.1",
    "pytest>=8.4.2",
    "taxcalc>=6.2.1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
